//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreLancer.Shaders
{
    using System;
    
    public class AllShaders
    {
        private static bool iscompiled = false;
        public static void Compile()
        {
            if (iscompiled)
            {
                return;
            }
            iscompiled = true;
            ShaderVariables.Log("Compiling all shaders");
            AsteroidBand.Compile();
            Atmosphere.Compile();
            Basic_PositionColor.Compile();
            Basic_PositionNormalColorTexture.Compile();
            Basic_PositionNormalTexture.Compile();
            Basic_PositionNormalTextureTwo.Compile();
            Basic_PositionTexture.Compile();
            Basic_Skinned.Compile();
            Billboard.Compile();
            DepthPass_AlphaTest.Compile();
            DepthPass_Normal.Compile();
            DetailMap2Dm1Msk2PassMaterial.Compile();
            DetailMapMaterial.Compile();
            IllumDetailMapMaterial.Compile();
            Masked2DetailMapMaterial.Compile();
            NebulaExtPuff.Compile();
            NebulaInterior.Compile();
            NebulaMaterial.Compile();
            Nomad.Compile();
            Normals.Compile();
            Particle.Compile();
            PhysicsDebug.Compile();
            Polyline.Compile();
            Projectile.Compile();
            SunRadial.Compile();
            SunSpine.Compile();
        }
    }
}
