//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreLancer.Shaders
{
    using System;
    
    public class Atmosphere
    {
        static ShaderVariables[] variants;
        private static bool iscompiled = false;
        private static int GetIndex(ShaderFeatures features)
        {
            ShaderFeatures masked = (features & ((ShaderFeatures)(16)));
            if ((masked == ((ShaderFeatures)(16))))
            {
                return 1;
            }
            return 0;
        }
        public static ShaderVariables Get(ShaderFeatures features)
        {
            AllShaders.Compile();
            return variants[GetIndex(features)];
        }
        public static ShaderVariables Get()
        {
            AllShaders.Compile();
            return variants[0];
        }
        internal static void Compile(string sourceBundle)
        {
            if (iscompiled)
            {
                return;
            }
            iscompiled = true;
            ShaderVariables.Log("Compiling Atmosphere");
            variants = new ShaderVariables[2];
            if (GLExtensions.Features430)
            {
                variants[0] = ShaderVariables.Compile(sourceBundle.Substring(16782, 1548), sourceBundle.Substring(18330, 6659));
                variants[1] = ShaderVariables.Compile(sourceBundle.Substring(31386, 4476), sourceBundle.Substring(35862, 2603));
            }
            else
            {
                variants[0] = ShaderVariables.Compile(sourceBundle.Substring(11521, 1207), sourceBundle.Substring(12728, 4054));
                variants[1] = ShaderVariables.Compile(sourceBundle.Substring(24989, 4135), sourceBundle.Substring(29124, 2262));
            }
        }
    }
}
