//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreLancer.Shaders
{
    using System;
    
    public class Atmosphere
    {
        static ShaderVariables[] variants;
        private static bool iscompiled = false;
        private static int GetIndex(ShaderFeatures features)
        {
            ShaderFeatures masked = (features & ((ShaderFeatures)(16)));
            if ((masked == ((ShaderFeatures)(16))))
            {
                return 1;
            }
            return 0;
        }
        public static ShaderVariables Get(ShaderFeatures features)
        {
            AllShaders.Compile();
            return variants[GetIndex(features)];
        }
        public static ShaderVariables Get()
        {
            AllShaders.Compile();
            return variants[0];
        }
        internal static void Compile(string sourceBundle)
        {
            if (iscompiled)
            {
                return;
            }
            iscompiled = true;
            ShaderVariables.Log("Compiling Atmosphere");
            variants = new ShaderVariables[2];
            if (GLExtensions.Features430)
            {
                variants[0] = ShaderVariables.Compile(sourceBundle.Substring(17154, 1622), sourceBundle.Substring(18776, 6630));
                variants[1] = ShaderVariables.Compile(sourceBundle.Substring(31853, 4555), sourceBundle.Substring(36408, 2574));
            }
            else
            {
                variants[0] = ShaderVariables.Compile(sourceBundle.Substring(11848, 1281), sourceBundle.Substring(13129, 4025));
                variants[1] = ShaderVariables.Compile(sourceBundle.Substring(25406, 4214), sourceBundle.Substring(29620, 2233));
            }
        }
    }
}
