//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreLancer.Shaders
{
    using System;
    
    public class Basic_PositionNormalTexture
    {
        static ShaderVariables[] variants;
        private static bool iscompiled = false;
        private static int GetIndex(ShaderFeatures features)
        {
            ShaderFeatures masked = (features & ((ShaderFeatures)(151)));
            if ((masked == ((ShaderFeatures)(16))))
            {
                return 1;
            }
            if ((masked == ((ShaderFeatures)(1))))
            {
                return 2;
            }
            if ((masked == ((ShaderFeatures)(17))))
            {
                return 3;
            }
            if ((masked == ((ShaderFeatures)(128))))
            {
                return 4;
            }
            if ((masked == ((ShaderFeatures)(144))))
            {
                return 5;
            }
            if ((masked == ((ShaderFeatures)(129))))
            {
                return 6;
            }
            if ((masked == ((ShaderFeatures)(145))))
            {
                return 7;
            }
            if ((masked == ((ShaderFeatures)(2))))
            {
                return 8;
            }
            if ((masked == ((ShaderFeatures)(18))))
            {
                return 9;
            }
            if ((masked == ((ShaderFeatures)(3))))
            {
                return 10;
            }
            if ((masked == ((ShaderFeatures)(19))))
            {
                return 11;
            }
            if ((masked == ((ShaderFeatures)(130))))
            {
                return 12;
            }
            if ((masked == ((ShaderFeatures)(146))))
            {
                return 13;
            }
            if ((masked == ((ShaderFeatures)(131))))
            {
                return 14;
            }
            if ((masked == ((ShaderFeatures)(147))))
            {
                return 15;
            }
            if ((masked == ((ShaderFeatures)(4))))
            {
                return 16;
            }
            if ((masked == ((ShaderFeatures)(20))))
            {
                return 17;
            }
            if ((masked == ((ShaderFeatures)(5))))
            {
                return 18;
            }
            if ((masked == ((ShaderFeatures)(21))))
            {
                return 19;
            }
            if ((masked == ((ShaderFeatures)(132))))
            {
                return 20;
            }
            if ((masked == ((ShaderFeatures)(148))))
            {
                return 21;
            }
            if ((masked == ((ShaderFeatures)(133))))
            {
                return 22;
            }
            if ((masked == ((ShaderFeatures)(149))))
            {
                return 23;
            }
            if ((masked == ((ShaderFeatures)(6))))
            {
                return 24;
            }
            if ((masked == ((ShaderFeatures)(22))))
            {
                return 25;
            }
            if ((masked == ((ShaderFeatures)(7))))
            {
                return 26;
            }
            if ((masked == ((ShaderFeatures)(23))))
            {
                return 27;
            }
            if ((masked == ((ShaderFeatures)(134))))
            {
                return 28;
            }
            if ((masked == ((ShaderFeatures)(150))))
            {
                return 29;
            }
            if ((masked == ((ShaderFeatures)(135))))
            {
                return 30;
            }
            if ((masked == ((ShaderFeatures)(151))))
            {
                return 31;
            }
            return 0;
        }
        public static ShaderVariables Get(LibreLancer.Graphics.RenderContext device, ShaderFeatures features)
        {
            AllShaders.Compile(device);
            return variants[GetIndex(features)];
        }
        public static ShaderVariables Get(LibreLancer.Graphics.RenderContext device)
        {
            AllShaders.Compile(device);
            return variants[0];
        }
        internal static void Compile(LibreLancer.Graphics.RenderContext device, string sourceBundle)
        {
            if (iscompiled)
            {
                return;
            }
            iscompiled = true;
            ShaderVariables.Log("Compiling Basic_PositionNormalTexture");
            variants = new ShaderVariables[32];
            variants[0] = ShaderVariables.Compile(device, sourceBundle.Substring(82666, 1399), sourceBundle.Substring(18061, 4181));
            variants[1] = ShaderVariables.Compile(device, sourceBundle.Substring(84065, 1819), sourceBundle.Substring(85884, 4383));
            variants[2] = ShaderVariables.Compile(device, sourceBundle.Substring(82666, 1399), sourceBundle.Substring(22242, 4235));
            variants[3] = ShaderVariables.Compile(device, sourceBundle.Substring(84065, 1819), sourceBundle.Substring(90267, 4437));
            variants[4] = ShaderVariables.Compile(device, sourceBundle.Substring(94704, 4323), sourceBundle.Substring(30544, 2389));
            variants[5] = ShaderVariables.Compile(device, sourceBundle.Substring(99027, 4743), sourceBundle.Substring(103770, 2591));
            variants[6] = ShaderVariables.Compile(device, sourceBundle.Substring(94704, 4323), sourceBundle.Substring(32933, 2443));
            variants[7] = ShaderVariables.Compile(device, sourceBundle.Substring(99027, 4743), sourceBundle.Substring(106361, 2645));
            variants[8] = ShaderVariables.Compile(device, sourceBundle.Substring(82666, 1399), sourceBundle.Substring(35376, 4225));
            variants[9] = ShaderVariables.Compile(device, sourceBundle.Substring(84065, 1819), sourceBundle.Substring(109006, 4427));
            variants[10] = ShaderVariables.Compile(device, sourceBundle.Substring(82666, 1399), sourceBundle.Substring(39601, 4279));
            variants[11] = ShaderVariables.Compile(device, sourceBundle.Substring(84065, 1819), sourceBundle.Substring(113433, 4481));
            variants[12] = ShaderVariables.Compile(device, sourceBundle.Substring(94704, 4323), sourceBundle.Substring(43880, 2433));
            variants[13] = ShaderVariables.Compile(device, sourceBundle.Substring(99027, 4743), sourceBundle.Substring(117914, 2635));
            variants[14] = ShaderVariables.Compile(device, sourceBundle.Substring(94704, 4323), sourceBundle.Substring(46313, 2487));
            variants[15] = ShaderVariables.Compile(device, sourceBundle.Substring(99027, 4743), sourceBundle.Substring(120549, 2689));
            variants[16] = ShaderVariables.Compile(device, sourceBundle.Substring(82666, 1399), sourceBundle.Substring(48800, 4375));
            variants[17] = ShaderVariables.Compile(device, sourceBundle.Substring(84065, 1819), sourceBundle.Substring(123238, 4577));
            variants[18] = ShaderVariables.Compile(device, sourceBundle.Substring(82666, 1399), sourceBundle.Substring(53175, 4429));
            variants[19] = ShaderVariables.Compile(device, sourceBundle.Substring(84065, 1819), sourceBundle.Substring(127815, 4631));
            variants[20] = ShaderVariables.Compile(device, sourceBundle.Substring(94704, 4323), sourceBundle.Substring(57604, 2583));
            variants[21] = ShaderVariables.Compile(device, sourceBundle.Substring(99027, 4743), sourceBundle.Substring(132446, 2785));
            variants[22] = ShaderVariables.Compile(device, sourceBundle.Substring(94704, 4323), sourceBundle.Substring(60187, 2637));
            variants[23] = ShaderVariables.Compile(device, sourceBundle.Substring(99027, 4743), sourceBundle.Substring(135231, 2839));
            variants[24] = ShaderVariables.Compile(device, sourceBundle.Substring(82666, 1399), sourceBundle.Substring(62824, 4419));
            variants[25] = ShaderVariables.Compile(device, sourceBundle.Substring(84065, 1819), sourceBundle.Substring(138070, 4621));
            variants[26] = ShaderVariables.Compile(device, sourceBundle.Substring(82666, 1399), sourceBundle.Substring(67243, 4473));
            variants[27] = ShaderVariables.Compile(device, sourceBundle.Substring(84065, 1819), sourceBundle.Substring(142691, 4675));
            variants[28] = ShaderVariables.Compile(device, sourceBundle.Substring(94704, 4323), sourceBundle.Substring(71716, 2627));
            variants[29] = ShaderVariables.Compile(device, sourceBundle.Substring(99027, 4743), sourceBundle.Substring(147366, 2829));
            variants[30] = ShaderVariables.Compile(device, sourceBundle.Substring(94704, 4323), sourceBundle.Substring(74343, 2681));
            variants[31] = ShaderVariables.Compile(device, sourceBundle.Substring(99027, 4743), sourceBundle.Substring(150195, 2883));
        }
    }
}
