//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreLancer.Shaders
{
    using System;
    
    public class DetailMapMaterial
    {
        static ShaderVariables[] variants;
        private static bool iscompiled = false;
        private static int GetIndex(ShaderFeatures features)
        {
            ShaderFeatures masked = (features & ((ShaderFeatures)(16)));
            if ((masked == ((ShaderFeatures)(16))))
            {
                return 1;
            }
            return 0;
        }
        public static ShaderVariables Get(LibreLancer.Graphics.RenderContext device, ShaderFeatures features)
        {
            AllShaders.Compile(device);
            return variants[GetIndex(features)];
        }
        public static ShaderVariables Get(LibreLancer.Graphics.RenderContext device)
        {
            AllShaders.Compile(device);
            return variants[0];
        }
        internal static void Compile(LibreLancer.Graphics.RenderContext device, string sourceBundle)
        {
            if (iscompiled)
            {
                return;
            }
            iscompiled = true;
            ShaderVariables.Log("Compiling DetailMapMaterial");
            variants = new ShaderVariables[2];
            if (device.HasFeature(LibreLancer.Graphics.GraphicsFeature.Features430))
            {
                variants[0] = ShaderVariables.Compile(device, sourceBundle.Substring(251574, 1545), sourceBundle.Substring(278286, 6814));
                variants[1] = ShaderVariables.Compile(device, sourceBundle.Substring(266725, 4472), sourceBundle.Substring(287517, 2758));
            }
            else
            {
                variants[0] = ShaderVariables.Compile(device, sourceBundle.Substring(246039, 1204), sourceBundle.Substring(274077, 4209));
                variants[1] = ShaderVariables.Compile(device, sourceBundle.Substring(260055, 4131), sourceBundle.Substring(285100, 2417));
            }
        }
    }
}
