//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreLancer.Shaders
{
    using System;
    
    public class PBR
    {
        static ShaderVariables[] variants;
        private static bool iscompiled = false;
        private static int GetIndex(ShaderFeatures features)
        {
            ShaderFeatures masked = (features & ((ShaderFeatures)(62)));
            if ((masked == ((ShaderFeatures)(2))))
            {
                return 1;
            }
            if ((masked == ((ShaderFeatures)(16))))
            {
                return 2;
            }
            if ((masked == ((ShaderFeatures)(18))))
            {
                return 3;
            }
            if ((masked == ((ShaderFeatures)(4))))
            {
                return 4;
            }
            if ((masked == ((ShaderFeatures)(6))))
            {
                return 5;
            }
            if ((masked == ((ShaderFeatures)(20))))
            {
                return 6;
            }
            if ((masked == ((ShaderFeatures)(22))))
            {
                return 7;
            }
            if ((masked == ((ShaderFeatures)(8))))
            {
                return 8;
            }
            if ((masked == ((ShaderFeatures)(10))))
            {
                return 9;
            }
            if ((masked == ((ShaderFeatures)(24))))
            {
                return 10;
            }
            if ((masked == ((ShaderFeatures)(26))))
            {
                return 11;
            }
            if ((masked == ((ShaderFeatures)(12))))
            {
                return 12;
            }
            if ((masked == ((ShaderFeatures)(14))))
            {
                return 13;
            }
            if ((masked == ((ShaderFeatures)(28))))
            {
                return 14;
            }
            if ((masked == ((ShaderFeatures)(30))))
            {
                return 15;
            }
            if ((masked == ((ShaderFeatures)(32))))
            {
                return 16;
            }
            if ((masked == ((ShaderFeatures)(34))))
            {
                return 17;
            }
            if ((masked == ((ShaderFeatures)(48))))
            {
                return 18;
            }
            if ((masked == ((ShaderFeatures)(50))))
            {
                return 19;
            }
            if ((masked == ((ShaderFeatures)(36))))
            {
                return 20;
            }
            if ((masked == ((ShaderFeatures)(38))))
            {
                return 21;
            }
            if ((masked == ((ShaderFeatures)(52))))
            {
                return 22;
            }
            if ((masked == ((ShaderFeatures)(54))))
            {
                return 23;
            }
            if ((masked == ((ShaderFeatures)(40))))
            {
                return 24;
            }
            if ((masked == ((ShaderFeatures)(42))))
            {
                return 25;
            }
            if ((masked == ((ShaderFeatures)(56))))
            {
                return 26;
            }
            if ((masked == ((ShaderFeatures)(58))))
            {
                return 27;
            }
            if ((masked == ((ShaderFeatures)(44))))
            {
                return 28;
            }
            if ((masked == ((ShaderFeatures)(46))))
            {
                return 29;
            }
            if ((masked == ((ShaderFeatures)(60))))
            {
                return 30;
            }
            if ((masked == ((ShaderFeatures)(62))))
            {
                return 31;
            }
            return 0;
        }
        public static ShaderVariables Get(LibreLancer.Graphics.RenderContext device, ShaderFeatures features)
        {
            AllShaders.Compile(device);
            return variants[GetIndex(features)];
        }
        public static ShaderVariables Get(LibreLancer.Graphics.RenderContext device)
        {
            AllShaders.Compile(device);
            return variants[0];
        }
        internal static void Compile(LibreLancer.Graphics.RenderContext device, string sourceBundle)
        {
            if (iscompiled)
            {
                return;
            }
            iscompiled = true;
            ShaderVariables.Log("Compiling PBR");
            variants = new ShaderVariables[32];
            variants[0] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(223958, 6310));
            variants[1] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(230268, 6403));
            variants[2] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(238086, 6507));
            variants[3] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(244593, 6600));
            variants[4] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(223958, 6310));
            variants[5] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(230268, 6403));
            variants[6] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(238086, 6507));
            variants[7] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(244593, 6600));
            variants[8] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(251193, 6376));
            variants[9] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(257569, 6469));
            variants[10] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(264038, 6573));
            variants[11] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(270611, 6666));
            variants[12] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(251193, 6376));
            variants[13] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(257569, 6469));
            variants[14] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(264038, 6573));
            variants[15] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(270611, 6666));
            variants[16] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(277277, 6376));
            variants[17] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(283653, 6469));
            variants[18] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(290122, 6573));
            variants[19] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(296695, 6666));
            variants[20] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(277277, 6376));
            variants[21] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(283653, 6469));
            variants[22] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(290122, 6573));
            variants[23] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(296695, 6666));
            variants[24] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(303361, 6442));
            variants[25] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(309803, 6535));
            variants[26] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(316338, 6639));
            variants[27] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(322977, 6732));
            variants[28] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(303361, 6442));
            variants[29] = ShaderVariables.Compile(device, sourceBundle.Substring(222963, 995), sourceBundle.Substring(309803, 6535));
            variants[30] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(316338, 6639));
            variants[31] = ShaderVariables.Compile(device, sourceBundle.Substring(236671, 1415), sourceBundle.Substring(322977, 6732));
        }
    }
}
