//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreLancer.Shaders
{
    using System;
    
    [Flags()]
    public enum ShaderFeatures
    {
        None = 0,
        ALPHATEST_ENABLED = 1,
        ET_ENABLED = 2,
        FADE_ENABLED = 4,
        METALMAP = 8,
        NORMALMAP = 16,
        ROUGHMAP = 32,
        VERTEX_DIFFUSE = 64,
        VERTEX_LIGHTING = 128,
    }
}
