// See https://aka.ms/new-console-template for more information

using System.Text;
using System.Text.Json;
using ImPlotBindingsGenerator;

Dictionary<string, FuncDefinition[]> defs = JsonSerializer.Deserialize<Dictionary<string, FuncDefinition[]>>(File.ReadAllText("definitions.json"))!;
Dictionary<string, string> typedefs = JsonSerializer.Deserialize <Dictionary<string, string>>(File.ReadAllText("typedef_dicts.json"))!;
EnumsDefinition enums = JsonSerializer.Deserialize<EnumsDefinition>(File.ReadAllText("structs_and_enums.json"))!;

List<FuncDefinition> allFunctions = new();
foreach (var d in defs)
{
    foreach (var f in d.Value)
    {
        // Not generating internal, va_list or struct methods.
        // Or _LJ methods (?)
        // Also exclude sbyte* and byte* overloads
        if (f.location.Contains("internal"))
            continue;
        if (f.args.Contains("...") || f.args.Contains("va_list"))
            continue;
        if (f.ov_cimguiname.EndsWith("_LJ") ||
            f.ov_cimguiname.Contains("_U8Ptr") ||
            f.ov_cimguiname.Contains("_S8Ptr"))
            continue;
        if (f.constructor || f.destructor)
            continue;
        if (f.stname != "")
            continue;

        allFunctions.Add(f);
    }
}

ShimFunctions.Write(allFunctions, typedefs);


using var cs_enums = new StreamWriter("Enums.cs");
cs_enums.WriteLine(@"// <auto-generated/>
using System;

namespace LibreLancer.ImUI.ImPlot;
");

HashSet<string> genEnums = new();
genEnums.Add("ImGuiMouseButton");

Dictionary<string, string> enumValues = new();

foreach (var e in enums.enums)
{
    if (enums.locations.TryGetValue(e.Key, out var loc) &&
        loc.Contains("internal"))
        continue;
    if(e.Value.Any(x => x.value.Contains("<<")))
        cs_enums.WriteLine("[Flags]");

    cs_enums.WriteLine($"public enum {e.Key.TrimEnd('_')}");
    genEnums.Add(e.Key.TrimEnd('_'));
    cs_enums.WriteLine("{");
    foreach (var v in e.Value)
    {
        var n = v.name;
        if (v.name.StartsWith(e.Key))
            n = v.name.Substring(e.Key.Length);
        cs_enums.WriteLine($"    {n} = {v.calc_value},");
        enumValues[v.name] = $"{e.Key.TrimEnd('_')}.{n}";
    }
    cs_enums.WriteLine("}\n");
}

using var natives = new StreamWriter("ImPlotNative.cs");

natives.WriteLine(@"// <auto-generated/>
#nullable disable
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using ImGuiNET;

namespace LibreLancer.ImUI.ImPlot;

static unsafe class ImPlotNative
{");

foreach (var f in allFunctions)
{
    var processedArgs = TypeHandling.CsNativeTypes(f.args);
    var processedRet = TypeHandling.CsNativeTypes(f.ret);

    natives.WriteLine("    [DllImport(\"cimgui\")]");
    natives.WriteLine($"    public static extern {processedRet} {f.ov_cimguiname}{processedArgs};\n");
}
natives.WriteLine("}");

ManagedFunctions.Write(allFunctions, genEnums, enumValues);



