// See https://aka.ms/new-console-template for more information

using System.Text;
using System.Text.Json;
using ImPlotBindingsGenerator;

Dictionary<string, FuncDefinition[]> defs = JsonSerializer.Deserialize<Dictionary<string, FuncDefinition[]>>(File.ReadAllText("definitions.json"))!;
Dictionary<string, string> typedefs = JsonSerializer.Deserialize <Dictionary<string, string>>(File.ReadAllText("typedef_dicts.json"))!;
StructsAndEnums structsAndEnums = JsonSerializer.Deserialize<StructsAndEnums>(File.ReadAllText("structs_and_enums.json"))!;

List<FuncDefinition> allFunctions = new();

Dictionary<string, TypeKind> allTypes = new()
{
    { "ImVec2", TypeKind.Struct },
    { "ImVec4", TypeKind.Struct },
    { "ImU16", TypeKind.Enum },
    { "ImS16", TypeKind.Enum },
    { "ImU32", TypeKind.Enum },
    { "ImS32", TypeKind.Enum },
    { "ImU64", TypeKind.Enum },
    { "ImS64", TypeKind.Enum },
    { "ImPlotFormatter", TypeKind.Pointer },
    { "ImPlotTransform", TypeKind.Pointer },
    { "ImPlotGetter", TypeKind.Pointer },
    { "ImGuiContext", TypeKind.Pointer },
    { "ImDrawList", TypeKind.Struct }
};

foreach (var s in structsAndEnums.structs)
{
    if (structsAndEnums.locations.TryGetValue(s.Key, out var loc) &&
        loc.Contains("internal"))
        continue;
    allTypes[s.Key] = TypeKind.Struct;
}

foreach (var e in structsAndEnums.enums)
{
    if (structsAndEnums.locations.TryGetValue(e.Key, out var loc) &&
        loc.Contains("internal"))
        continue;
    allTypes[e.Key] = TypeKind.Enum;
}

foreach (var td in typedefs)
{
    if (td.Value == "int")
        allTypes[td.Key] = TypeKind.Enum;
}


foreach (var d in defs)
{
    foreach (var f in d.Value)
    {
        // Not generating internal, va_list or struct methods.
        // Or _LJ methods (?)
        // Also exclude sbyte* and byte* overloads
        if (f.location.Contains("internal"))
            continue;
        if (f.args.Contains("...") || f.args.Contains("va_list"))
            continue;
        if (f.ov_cimguiname.EndsWith("_LJ") ||
            f.ov_cimguiname.Contains("_U8Ptr") ||
            f.ov_cimguiname.Contains("_S8Ptr"))
            continue;
        if (f.constructor || f.destructor)
            continue;
        if (f.stname != "")
            continue;

        StringBuilder funcArgs = new();
        var srcSig = f.args.Substring(1, f.args.Length - 2).Split(',', StringSplitOptions.TrimEntries);

        funcArgs.Append("(");
        for (int i = 0; i < f.argsT.Length; i++)
        {
            var t = f.argsT[i];
            if (i != 0)
                funcArgs.Append(", ");
            string type = t.type;
            bool pointerType = false;
            foreach (var n in allTypes)
            {
                if (type.Contains(n.Key))
                {
                    type = type.Replace(n.Key, $"cimgui::{n.Key}");
                    break;
                }
            }
            bool arrayType = type.EndsWith("[]");
            if (arrayType)
                type = type.Substring(0, type.Length - 2);
            funcArgs.Append(type);
            funcArgs.Append(" ");
            funcArgs.Append(t.name);
            if (arrayType)
                funcArgs.Append("[]");
        }

        funcArgs.Append(")");
        f.CppFileArgs = funcArgs.ToString();
        var srcArgs = f.call_args.Substring(1, f.call_args.Length - 2).Split(',', StringSplitOptions.TrimEntries);

        StringBuilder funcCall = new();
        funcCall.Append("(");
        for (int i = 0; i < f.argsT.Length; i++)
        {
            var t = f.argsT[i];
            if (i != 0)
                funcCall.Append(", ");
            var arg = srcArgs[i];
            funcCall.Append(TypeConversions.CToCppCast(t.type, arg, allTypes));
        }
        funcCall.Append(")");
        f.CppFileCall = funcCall.ToString();
        allFunctions.Add(f);
    }
}

ShimFunctions.Write(allFunctions, typedefs, structsAndEnums, allTypes);


using var cs_enums = new StreamWriter("Enums.cs");
cs_enums.WriteLine(@"// <auto-generated/>
using System;

namespace LibreLancer.ImUI.ImPlot;
");

HashSet<string> genEnums = new();
genEnums.Add("ImGuiMouseButton");

Dictionary<string, string> enumValues = new();

foreach (var e in structsAndEnums.enums)
{
    if (structsAndEnums.locations.TryGetValue(e.Key, out var loc) &&
        loc.Contains("internal"))
        continue;
    if(e.Value.Any(x => x.value.Contains("<<")))
        cs_enums.WriteLine("[Flags]");

    cs_enums.WriteLine($"public enum {e.Key.TrimEnd('_')}");
    genEnums.Add(e.Key.TrimEnd('_'));
    cs_enums.WriteLine("{");
    foreach (var v in e.Value)
    {
        var n = v.name;
        if (v.name.StartsWith(e.Key))
            n = v.name.Substring(e.Key.Length);
        cs_enums.WriteLine($"    {n} = {v.calc_value},");
        enumValues[v.name] = $"{e.Key.TrimEnd('_')}.{n}";
    }
    cs_enums.WriteLine("}\n");
}

using var natives = new StreamWriter("ImPlotNative.cs");

natives.WriteLine(@"// <auto-generated/>
#nullable disable
using System;
using System.Numerics;
using System.Runtime.InteropServices;
using ImGuiNET;

namespace LibreLancer.ImUI.ImPlot;

static unsafe class ImPlotNative
{");

foreach (var f in allFunctions)
{
    var processedArgs = TypeHandling.CsNativeTypes(f.args);
    var processedRet = TypeHandling.CsNativeTypes(f.ret);

    natives.WriteLine("    [DllImport(\"cimgui\")]");
    natives.WriteLine($"    public static extern {processedRet} {f.ov_cimguiname}{processedArgs};\n");
}
natives.WriteLine("}");

ManagedFunctions.Write(allFunctions, genEnums, enumValues);



