// MIT License - Copyright (c) Callum McGing
// This file is subject to the terms and conditions defined in
// LICENSE, which is part of this source code package

internal static class DecompressTemplate
{
    public const string Text = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Text;

namespace {NAMESPACE}
{
    static class ShCompHelper
    {
        public static string FromArray(byte[] s)
        {
            using (var strmIn = new MemoryStream(s))
            {
                using (var strmOut = new MemoryStream())
                {
                    using (var comp = new {COMPRESS}Stream(strmIn, CompressionMode.Decompress))
                    {
                        comp.CopyTo(strmOut);
                    }
        
                    var bytes = strmOut.ToArray();
                    return Encoding.UTF8.GetString(bytes);
                }
            }
        }
    }
}
";
}