// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;


namespace LLShaderCompiler.SPIRVCross;

[StructLayout(LayoutKind.Sequential, Pack = 1)]
public record struct spvc_bool(byte Value)
{
	public static implicit operator byte(spvc_bool self) => self.Value;
	public static implicit operator spvc_bool(byte self) => new(self);
	public static implicit operator bool(spvc_bool self) => self.Value != 0;
	public static implicit operator spvc_bool(bool self) => self ? new(1) : new(0);
}
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public record struct spvc_constant_id(uint Value)
{
	public static implicit operator uint(spvc_constant_id self) => self.Value;
	public static implicit operator spvc_constant_id(uint self) => new(self);
}
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public record struct spvc_variable_id(uint Value)
{
	public static implicit operator uint(spvc_variable_id self) => self.Value;
	public static implicit operator spvc_variable_id(uint self) => new(self);
}
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public record struct spvc_type_id(uint Value)
{
	public static implicit operator uint(spvc_type_id self) => self.Value;
	public static implicit operator spvc_type_id(uint self) => new(self);
}
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public record struct spvc_hlsl_binding_flags(uint Value)
{
	public static implicit operator uint(spvc_hlsl_binding_flags self) => self.Value;
	public static implicit operator spvc_hlsl_binding_flags(uint self) => new(self);
}
[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_reflected_resource
{
	public spvc_variable_id id;
	public spvc_type_id base_type_id;
	public spvc_type_id type_id;
	public unsafe byte* name;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_reflected_builtin_resource
{
	public SpvBuiltIn builtin;
	public spvc_type_id value_type_id;
	public spvc_reflected_resource resource;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_entry_point
{
	public SpvExecutionModel execution_model;
	public unsafe byte* name;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_combined_image_sampler
{
	public spvc_variable_id combined_id;
	public spvc_variable_id image_id;
	public spvc_variable_id sampler_id;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_specialization_constant
{
	public spvc_constant_id id;
	public uint constant_id;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_buffer_range
{
	public uint index;
	public nuint offset;
	public nuint range;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_hlsl_root_constants
{
	public uint start;
	public uint end;
	public uint binding;
	public uint space;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_hlsl_vertex_attribute_remap
{
	public uint location;
	public unsafe byte* semantic;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_msl_vertex_attribute
{
	public uint location;
	public uint msl_buffer;
	public uint msl_offset;
	public uint msl_stride;
	public spvc_bool per_instance;
	public spvc_msl_shader_variable_format format;
	public SpvBuiltIn builtin;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_msl_shader_interface_var
{
	public uint location;
	public spvc_msl_shader_variable_format format;
	public SpvBuiltIn builtin;
	public uint vecsize;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_msl_shader_interface_var_2
{
	public uint location;
	public spvc_msl_shader_variable_format format;
	public SpvBuiltIn builtin;
	public uint vecsize;
	public spvc_msl_shader_variable_rate rate;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_msl_resource_binding
{
	public SpvExecutionModel stage;
	public uint desc_set;
	public uint binding;
	public uint msl_buffer;
	public uint msl_texture;
	public uint msl_sampler;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_msl_resource_binding_2
{
	public SpvExecutionModel stage;
	public uint desc_set;
	public uint binding;
	public uint count;
	public uint msl_buffer;
	public uint msl_texture;
	public uint msl_sampler;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_msl_constexpr_sampler
{
	public spvc_msl_sampler_coord coord;
	public spvc_msl_sampler_filter min_filter;
	public spvc_msl_sampler_filter mag_filter;
	public spvc_msl_sampler_mip_filter mip_filter;
	public spvc_msl_sampler_address s_address;
	public spvc_msl_sampler_address t_address;
	public spvc_msl_sampler_address r_address;
	public spvc_msl_sampler_compare_func compare_func;
	public spvc_msl_sampler_border_color border_color;
	public float lod_clamp_min;
	public float lod_clamp_max;
	public int max_anisotropy;
	public spvc_bool compare_enable;
	public spvc_bool lod_clamp_enable;
	public spvc_bool anisotropy_enable;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_msl_sampler_ycbcr_conversion
{
	public uint planes;
	public spvc_msl_format_resolution resolution;
	public spvc_msl_sampler_filter chroma_filter;
	public spvc_msl_chroma_location x_chroma_offset;
	public spvc_msl_chroma_location y_chroma_offset;
	public spvc_msl_component_swizzle swizzle_0;
	public spvc_msl_component_swizzle swizzle_1;
	public spvc_msl_component_swizzle swizzle_2;
	public spvc_msl_component_swizzle swizzle_3;
	public spvc_msl_sampler_ycbcr_model_conversion ycbcr_model;
	public spvc_msl_sampler_ycbcr_range ycbcr_range;
	public uint bpc;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_hlsl_resource_binding_mapping
{
	public uint register_space;
	public uint register_binding;
}

[StructLayout(LayoutKind.Sequential)]
public partial struct spvc_hlsl_resource_binding
{
	public SpvExecutionModel stage;
	public uint desc_set;
	public uint binding;
	public spvc_hlsl_resource_binding_mapping cbv;
	public spvc_hlsl_resource_binding_mapping uav;
	public spvc_hlsl_resource_binding_mapping srv;
	public spvc_hlsl_resource_binding_mapping sampler;
}

