#!/bin/bash
# Script to check if dependencies for build are installed
# Blacklists broken mono versions

check_command() {
    command -v $1 >/dev/null 2>&1 || { echo >&2 "Cannot find $1 on PATH"; exit 1; }
}

blacklist_version() {
    if mono --version | grep -F -q $1 ; then
        echo Mono version $1 does not work with Cake. $2
        exit 1
    fi
}

check_command mono
check_command cmake
check_command make

# Mono Version Blacklist (version, reason)
blacklist_version 6.8.0.96 "Bug #18508"

