#!/bin/bash
extract_conf() {
cat << _EOF > my.cnf
[client]
socket		= ./dbdata/mysqld.sock
port		= 60043

[mysqld]
datadir		= ./dbdata
aria-log-dir-path = .
socket		= ./mysqld.sock
port		= 60043
skip-external-locking
key_buffer_size = 16M
max_allowed_packet = 1M
table_open_cache = 64
sort_buffer_size = 512K
net_buffer_length = 8K
read_buffer_size = 256K
read_rnd_buffer_size = 512K
myisam_sort_buffer_size = 8M
log-bin=mysql-bin
binlog_format=mixed
server-id	= 1


[mysqldump]
quick
max_allowed_packet = 16M

[mysql]
no-auto-rehash

[myisamchk]
key_buffer_size = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[mysqlhotcopy]
interactive-timeout
_EOF
}

sql_file() {
cat << _EOF > setup.sql
CREATE USER 'librelancer'@'localhost' IDENTIFIED BY 'librelancerDEVPASSWORD_THISISINSECURE';
GRANT ALL PRIVILEGES ON *.* to 'librelancer'@'localhost' WITH GRANT OPTION;
_EOF
}
cd ../bin
if [ ! -d "mysql" ]; then
	mkdir -p mysql/dbdata
	cd mysql
	extract_conf
	mysql_install_db --basedir=/usr --defaults-file=my.cnf
	sql_file
	echo INIT COMPLETE. PLEASE RUN THIS AGAIN AND SETUP THE USER WITH ./mysql-usersetup
	exit 0
fi
cd mysql
echo STARTING MYSQLD - USE CTRL+\\ TO QUIT
mysqld --defaults-file=my.cnf 