// <auto-generated/>
using System;

namespace LibreLancer.ImUI.ImPlot;

public enum ImAxis
{
    X1 = 0,
    X2 = 1,
    X3 = 2,
    Y1 = 3,
    Y2 = 4,
    Y3 = 5,
    COUNT = 6,
}

[Flags]
public enum ImPlotAxisFlags
{
    None = 0,
    NoLabel = 1,
    NoGridLines = 2,
    NoTickMarks = 4,
    NoTickLabels = 8,
    NoInitialFit = 16,
    NoMenus = 32,
    NoSideSwitch = 64,
    NoHighlight = 128,
    Opposite = 256,
    Foreground = 512,
    Invert = 1024,
    AutoFit = 2048,
    RangeFit = 4096,
    PanStretch = 8192,
    LockMin = 16384,
    LockMax = 32768,
    Lock = 49152,
    NoDecorations = 15,
    AuxDefault = 258,
}

[Flags]
public enum ImPlotBarGroupsFlags
{
    None = 0,
    Horizontal = 1024,
    Stacked = 2048,
}

[Flags]
public enum ImPlotBarsFlags
{
    None = 0,
    Horizontal = 1024,
}

public enum ImPlotBin
{
    Sqrt = -1,
    Sturges = -2,
    Rice = -3,
    Scott = -4,
}

public enum ImPlotBubblesFlags
{
    None = 0,
}

public enum ImPlotCol
{
    FrameBg = 0,
    PlotBg = 1,
    PlotBorder = 2,
    LegendBg = 3,
    LegendBorder = 4,
    LegendText = 5,
    TitleText = 6,
    InlayText = 7,
    AxisText = 8,
    AxisGrid = 9,
    AxisTick = 10,
    AxisBg = 11,
    AxisBgHovered = 12,
    AxisBgActive = 13,
    Selection = 14,
    Crosshairs = 15,
    COUNT = 16,
}

[Flags]
public enum ImPlotColormapScaleFlags
{
    None = 0,
    NoLabel = 1,
    Opposite = 2,
    Invert = 4,
}

public enum ImPlotColormap
{
    Deep = 0,
    Dark = 1,
    Pastel = 2,
    Paired = 3,
    Viridis = 4,
    Plasma = 5,
    Hot = 6,
    Cool = 7,
    Pink = 8,
    Jet = 9,
    Twilight = 10,
    RdBu = 11,
    BrBG = 12,
    PiYG = 13,
    Spectral = 14,
    Greys = 15,
}

public enum ImPlotCond
{
    None = 0,
    Always = 1,
    Once = 2,
}

public enum ImPlotDigitalFlags
{
    None = 0,
}

[Flags]
public enum ImPlotDragToolFlags
{
    None = 0,
    NoCursors = 1,
    NoFit = 2,
    NoInputs = 4,
    Delayed = 8,
}

public enum ImPlotDummyFlags
{
    None = 0,
}

[Flags]
public enum ImPlotErrorBarsFlags
{
    None = 0,
    Horizontal = 1024,
}

[Flags]
public enum ImPlotFlags
{
    None = 0,
    NoTitle = 1,
    NoLegend = 2,
    NoMouseText = 4,
    NoInputs = 8,
    NoMenus = 16,
    NoBoxSelect = 32,
    NoFrame = 64,
    Equal = 128,
    Crosshairs = 256,
    CanvasOnly = 55,
}

[Flags]
public enum ImPlotHeatmapFlags
{
    None = 0,
    ColMajor = 1024,
}

[Flags]
public enum ImPlotHistogramFlags
{
    None = 0,
    Horizontal = 1024,
    Cumulative = 2048,
    Density = 4096,
    NoOutliers = 8192,
    ColMajor = 16384,
}

public enum ImPlotImageFlags
{
    None = 0,
}

[Flags]
public enum ImPlotInfLinesFlags
{
    None = 0,
    Horizontal = 1024,
}

[Flags]
public enum ImPlotItemFlags
{
    None = 0,
    NoLegend = 1,
    NoFit = 2,
}

[Flags]
public enum ImPlotLegendFlags
{
    None = 0,
    NoButtons = 1,
    NoHighlightItem = 2,
    NoHighlightAxis = 4,
    NoMenus = 8,
    Outside = 16,
    Horizontal = 32,
    Sort = 64,
    Reverse = 128,
}

[Flags]
public enum ImPlotLineFlags
{
    None = 0,
    Segments = 1024,
    Loop = 2048,
    SkipNaN = 4096,
    NoClip = 8192,
    Shaded = 16384,
}

[Flags]
public enum ImPlotLocation
{
    Center = 0,
    North = 1,
    South = 2,
    West = 4,
    East = 8,
    NorthWest = 5,
    NorthEast = 9,
    SouthWest = 6,
    SouthEast = 10,
}

public enum ImPlotMarker
{
    None = -2,
    Auto = -1,
    Circle = 0,
    Square = 1,
    Diamond = 2,
    Up = 3,
    Down = 4,
    Left = 5,
    Right = 6,
    Cross = 7,
    Plus = 8,
    Asterisk = 9,
    COUNT = 10,
}

[Flags]
public enum ImPlotMouseTextFlags
{
    None = 0,
    NoAuxAxes = 1,
    NoFormat = 2,
    ShowAlways = 4,
}

[Flags]
public enum ImPlotPieChartFlags
{
    None = 0,
    Normalize = 1024,
    IgnoreHidden = 2048,
    Exploding = 4096,
}

public enum ImPlotProp
{
    LineColor = 0,
    LineWeight = 1,
    FillColor = 2,
    FillAlpha = 3,
    Marker = 4,
    MarkerSize = 5,
    MarkerLineColor = 6,
    MarkerFillColor = 7,
    Size = 8,
    Offset = 9,
    Stride = 10,
    Flags = 11,
}

public enum ImPlotScale
{
    Linear = 0,
    Time = 1,
    Log10 = 2,
    SymLog = 3,
}

[Flags]
public enum ImPlotScatterFlags
{
    None = 0,
    NoClip = 1024,
}

public enum ImPlotShadedFlags
{
    None = 0,
}

[Flags]
public enum ImPlotStairsFlags
{
    None = 0,
    PreStep = 1024,
    Shaded = 2048,
}

[Flags]
public enum ImPlotStemsFlags
{
    None = 0,
    Horizontal = 1024,
}

public enum ImPlotStyleVar
{
    PlotDefaultSize = 0,
    PlotMinSize = 1,
    PlotBorderSize = 2,
    MinorAlpha = 3,
    MajorTickLen = 4,
    MinorTickLen = 5,
    MajorTickSize = 6,
    MinorTickSize = 7,
    MajorGridSize = 8,
    MinorGridSize = 9,
    PlotPadding = 10,
    LabelPadding = 11,
    LegendPadding = 12,
    LegendInnerPadding = 13,
    LegendSpacing = 14,
    MousePosPadding = 15,
    AnnotationPadding = 16,
    FitPadding = 17,
    DigitalPadding = 18,
    DigitalSpacing = 19,
    COUNT = 20,
}

[Flags]
public enum ImPlotSubplotFlags
{
    None = 0,
    NoTitle = 1,
    NoLegend = 2,
    NoMenus = 4,
    NoResize = 8,
    NoAlign = 16,
    ShareItems = 32,
    LinkRows = 64,
    LinkCols = 128,
    LinkAllX = 256,
    LinkAllY = 512,
    ColMajor = 1024,
}

[Flags]
public enum ImPlotTextFlags
{
    None = 0,
    Vertical = 1024,
}

