#!/bin/bash
# Script for creating a minimal version of mpv for the Librelancer package script to bundle
mpv_build() {
	mkdir obj
	cd obj
	echo INSTALLING HOMEBREW
	git clone https://github.com/mxcl/homebrew.git
	export PATH="$(pwd)/homebrew/bin:/usr/bin:/usr/sbin:/sbin:/bin"
	brew update
	FFMPEG_VERSION=$(brew info ffmpeg | grep "ffmpeg:" | awk '{print $3}' | sed 's/,$//')
	echo INSTALLING FFMPEG DEPENDENCIES FOR FFMPEG $FFMPEG_VERSION
	brew install --only-dependencies ffmpeg
	echo "INSTALLING MINIMAL FFMPEG (no programs, encoders, https, devices, filters)"
	curl https://ffmpeg.org/releases/ffmpeg-$FFMPEG_VERSION.tar.bz2 > ffmpeg.tar.bz2
	tar xjf ffmpeg.tar.bz2
	export FF_PREFIX=$(pwd)/homebrew/Cellar/ffmpeg/$FFMPEG_VERSION
	cd ffmpeg-$FFMPEG_VERSION
	./configure --disable-programs --disable-doc --enable-small --enable-shared --enable-pthreads --enable-avresample --disable-encoders --disable-devices --disable-sdl --disable-protocols --disable-filters --enable-filter=yadif --enable-protocol=file "--prefix=$FF_PREFIX"
	make
	make install
	cd ..
	brew link ffmpeg
	echo INSTALLING MPV
	brew install mpv --with-bundle
	cp -r homebrew/Cellar/mpv/*/mpv.app ../assets/.
	echo MPV OUTPUTTED TO: assets/mpv.app
	cd ..
	rm -rf obj
}

if [[ $1 == "--yes" ]]
then
	mpv_build
	exit 0
fi
echo "WARNING: This process will take a long time and use a large amount of bandwidth."
echo "If this is unacceptable, download a normal mpv bundle"
echo "(run with --yes to skip this message)"
read -p "Are you sure? [y/n]: " -n 1 -r
echo    # move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    mpv_build
fi
