#!/bin/bash
#CD TO SELF
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $dir
#Windows Build
echo Generating Windows Package
FOLDER_NAME=librelancer-$(git rev-parse --short  HEAD)-win
mkdir -p packages
cp -r ../bin/Release packages/$FOLDER_NAME
cp ../Credits.txt packages/$FOLDER_NAME/
cp ../LICENSE packages/$FOLDER_NAME/
echo "Source Code: https://github.com/Librelancer/Librelancer" > packages/$FOLDER_NAME/getsource.txt
#lgpl compliance
cp "../deps/openal-soft license.txt" packages/$FOLDER_NAME
mkdir -p packages/$FOLDER_NAME/LGPL
cd packages/$FOLDER_NAME/LGPL
wget $(cat ../../../../deps/openal-sourceurl.txt)
cd ../../..
#Bugged file?
rm packages/$FOLDER_NAME/.dll.config
#Remove debug
rm packages/$FOLDER_NAME/*.pdb
rm packages/$FOLDER_NAME/*.xml
cd packages
zip -r librelancer-daily-win.zip $FOLDER_NAME
rm -r $FOLDER_NAME
cd ..
#Linux Build
echo Generating Linux Package
FOLDER_NAME=librelancer-$(git rev-parse --short HEAD)-ubuntu-amd64
cd ..
./build.cimgui.unix
cd packaging
cp -r ../bin/Release packages/$FOLDER_NAME
cp ../Credits.txt packages/$FOLDER_NAME/
cp ../LICENSE packages/$FOLDER_NAME/
echo "Source Code: https://github.com/Librelancer/Librelancer" > packages/$FOLDER_NAME/getsource.txt
#Remove debug
rm packages/$FOLDER_NAME/*.pdb
rm packages/$FOLDER_NAME/*.xml
#Bugged file?
rm packages/$FOLDER_NAME/.dll.config
#Delete Windows native
rm -rf packages/$FOLDER_NAME/x86
rm -rf packages/$FOLDER_NAME/x64
cd packages
tar -czvf librelancer-daily-ubuntu-amd64.tar.gz $FOLDER_NAME
rm -r $FOLDER_NAME
cd ..
#Output Date Timestamp
echo $(date +%s) > packages/timestamp

 
